version: '3.9'

services:

  postgres-unit:
    build:
      context: ./database_postgres
      # dockerfile: ./database_postgres/Dockerfile
    container_name: postgres-db-test
    env_file:
      - ./database_postgres/.env
    ports:
      - 5432:5432
    # restart: unless-stopped
    restart: always