version: '3.9'

services:
  carterapp: 
    build:
      dockerfile: ../Scripts/dockerCarter/Dockerfile
      context: ../../CarterApp
    # network_mode: host
    networks:
      - hostout
    ports:
      - 80:80
    volumes:
      - ../../CarterApp/Data:/app/Data
    restart: always

networks:
  hostout:
    driver: bridge
